# Generated by Django 3.1.7 on 2021-04-04 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profilepic/patient')),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')], default=3)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('blood_group', models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, 'O+'), (8, 'O-')], default=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profilepic/Doctor/')),
                ('contact', models.CharField(max_length=20, null=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')], default=3)),
                ('address', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[(1, 'Eye Care'), (2, 'Skin Care'), (3, 'Surgery'), (4, 'Physical Therapy'), (5, 'Dental'), (6, 'General')], default='6', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
