# Generated by Django 3.1.7 on 2021-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.IntegerField(choices=[(1, 'Eye Care'), (2, 'Skin Care'), (3, 'Surgery'), (4, 'Physical Therapy'), (5, 'Dental'), (6, 'General'), (7, 'Cardiology')], default='6', max_length=50),
        ),
    ]
