# Generated by Django 3.0.5 on 2021-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210525_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='symptoms',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Eye Care', 'Eye Care'), ('Skin Care', 'Skin Care'), ('Surgery', 'Surgery'), ('Physical Therapy', 'Physical Therapy'), ('Dental', 'Dental'), ('General', 'General'), ('Cardiology', 'Cardiology')], default='Eye Care', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=50),
        ),
    ]
