# Generated by Django 3.0.5 on 2021-06-03 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210603_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptoms',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
