# Generated by Django 3.0.5 on 2021-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_appointment_appt_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default=3),
        ),
    ]
